### ISSUE TITLE
Correction needed in the SimpleServlet.java template

### ISSUE THREAD

**Issue by artika4biz** [Adobe-Marketing-Cloud/aem-guides#19]
This file needs a correction in the UID case:

private static final long serialVersion**Uid** = 1L;
private static final long serialVersion**UID** = 1L;

**Comment by davidjgonzalez** [comment]
@artika4biz sorry - can you link to the file in the repo that needs this update? I can't seem to find a file with this name in this repo... (or one that uses: serialVersionUid) .. is it on a different branch perhaps?

**Comment by artika4biz** [comment]
@davidjgonzalez Actually I opened this issue for the Aem Project Archetype:
[issue 120 ](https://github.com/Adobe-Marketing-Cloud/aem-project-archetype/issues/120).

You can consider this issue in aem-guides as a duplicate and close/remove it
